//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLevel
    {
        public AccessLevel()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid AccessLevelID { get; set; }
        public string AccessLevelDesc { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
