//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.DrugsPriceHistoties = new HashSet<DrugsPriceHistoty>();
            this.labTestsMaterials = new HashSet<labTestsMaterial>();
            this.Prescriptions = new HashSet<Prescription>();
            this.ServiceTreatmentDrugs = new HashSet<ServiceTreatmentDrug>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public System.Guid DrugID { get; set; }
        public string DrugName { get; set; }
        public string DrugDescription { get; set; }
        public Nullable<int> DrugQuantity { get; set; }
    
        public virtual ICollection<DrugsPriceHistoty> DrugsPriceHistoties { get; set; }
        public virtual ICollection<labTestsMaterial> labTestsMaterials { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual ICollection<ServiceTreatmentDrug> ServiceTreatmentDrugs { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
