//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugsPriceHistoty
    {
        public System.Guid DrugID { get; set; }
        public System.DateTime DrugPriceAdjDate { get; set; }
        public Nullable<decimal> DrugPrice { get; set; }
    
        public virtual Drug Drug { get; set; }
    }
}
