//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmpSalaries = new HashSet<EmpSalary>();
            this.Roosters = new HashSet<Rooster>();
            this.Stocks = new HashSet<Stock>();
            this.Visits = new HashSet<Visit>();
            this.ServiceTreatments = new HashSet<ServiceTreatment>();
        }
    
        public System.Guid EmployeeID { get; set; }
        public Nullable<System.Guid> EmployeeCategoryID { get; set; }
        public Nullable<System.Guid> EmpAccessLevelID { get; set; }
        public Nullable<System.DateTime> EmpStartDate { get; set; }
        public Nullable<System.DateTime> EmpEndDate { get; set; }
        public Nullable<System.DateTime> EmpPayDay { get; set; }
        public Nullable<decimal> EmpAccountBalance { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual EmployeeCategory EmployeeCategory { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<EmpSalary> EmpSalaries { get; set; }
        public virtual ICollection<Rooster> Roosters { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<ServiceTreatment> ServiceTreatments { get; set; }
    }
}
