//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public System.Guid EntityID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string TelNumber { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public Nullable<short> BranchCode { get; set; }
        public Nullable<short> SwiftCode { get; set; }
    
        public virtual Compagny Compagny { get; set; }
        public virtual Person Person { get; set; }
    }
}
