//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndentifcationType
    {
        public IndentifcationType()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public System.Guid IDType { get; set; }
        public string TypeName { get; set; }
        public string TypeDesc { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<Person> Persons { get; set; }
    }
}
