//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTest
    {
        public LabTest()
        {
            this.PatientsTests = new HashSet<PatientsTest>();
        }
    
        public System.Guid LabTestID { get; set; }
        public string LabTestDesc { get; set; }
        public Nullable<decimal> LabTestFee { get; set; }
    
        public virtual labTestsMaterial labTestsMaterial { get; set; }
        public virtual ICollection<PatientsTest> PatientsTests { get; set; }
    }
}
