//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public System.Guid PatientID { get; set; }
        public Nullable<decimal> Accountbalance { get; set; }
    
        public virtual IndentifcationType IndentifcationType { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
