//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientReferer
    {
        public PatientReferer()
        {
            this.ServiceTreatments = new HashSet<ServiceTreatment>();
        }
    
        public System.Guid PatientRefererID { get; set; }
        public string ClinicName { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<ServiceTreatment> ServiceTreatments { get; set; }
    }
}
