//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsTest
    {
        public System.Guid VisitID { get; set; }
        public System.Guid LabTestID { get; set; }
        public string TestPaid { get; set; }
    
        public virtual LabTest LabTest { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
