//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid PaymentSourceID { get; set; }
        public System.Guid PaymentDestID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.Guid PaymentModeID { get; set; }
    
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
