//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Payments = new HashSet<Payment>();
            this.Payments1 = new HashSet<Payment>();
        }
    
        public System.Guid PersonID { get; set; }
        public string Surname { get; set; }
        public string CellNumber { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.Guid> IDType { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Username { get; set; }
        public string Password1 { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual IndentifcationType IndentifcationType { get; set; }
        public virtual LogOnHistory LogOnHistory { get; set; }
        public virtual PatientReferer PatientReferer { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
    }
}
