//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTreatmentFeeHist
    {
        public System.Guid ServiceTreatmentID { get; set; }
        public System.DateTime ServiceFeeAdjDate { get; set; }
        public Nullable<decimal> ServiceTreatmentFee { get; set; }
    
        public virtual ServiceTreatmentType ServiceTreatmentType { get; set; }
    }
}
