//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSaintJean_Ori.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTreatmentType
    {
        public ServiceTreatmentType()
        {
            this.ServiceTreatmentDrugs = new HashSet<ServiceTreatmentDrug>();
            this.ServiceTreatmentFeeHists = new HashSet<ServiceTreatmentFeeHist>();
            this.ServiceTreatments = new HashSet<ServiceTreatment>();
        }
    
        public System.Guid ServiceTreatmentTypeID { get; set; }
        public string ServiceTreatmentDesc { get; set; }
    
        public virtual ICollection<ServiceTreatmentDrug> ServiceTreatmentDrugs { get; set; }
        public virtual ICollection<ServiceTreatmentFeeHist> ServiceTreatmentFeeHists { get; set; }
        public virtual ICollection<ServiceTreatment> ServiceTreatments { get; set; }
    }
}
